import type { Metadata } from "next";
import "./globals.css";
import Logo from "../components/icon/Logo";
import { BG_COLOR, TOOLBAR_MIN_HEIGHT } from "../constants/styles";
import { MENU_ITEMS } from "../constants/menu";
import MenuItem from "../components/ui/Menuitem";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`font-medium flex flex-col h-screen ${BG_COLOR} pt-2`}>
        <div className={`${TOOLBAR_MIN_HEIGHT} flex items-center px-6 gap-4`}>
          <Logo />
          <div className="flex gap-1">
            {MENU_ITEMS.map((item, index) => (
              <MenuItem key={index} icon={item.icon} label={item.label} href={item.href} />
            ))}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
